name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: yanghs81/yang
          stage: main
          yaml: |
            name: yang-svc
            app: node@20
            options:
              env:
                - name: SERVER_PORT
                  value: "5000"
                - name: SESSION_SECRET
                  value: abouttechsecret
                - name: SALTROUNDS
                  secret: SALTROUNDS
                - name: HOST
                  value: mariasvc
                - name: PORT
                  value: "3306"
                - name: USER
                  value: root
                - name: PASSWORD
                  value: "1234"
                - name: DB
                  value: picdb
              ports: "5000"
              install: npm ci
              start: node index.js
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: node
